version: '3.8'

services:

  db_test:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 10s
      timeout: 5s
      retries: 5

  web_tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "alembic upgrade head && pytest test_main.py"
    restart: always
    env_file:
      - .env_test
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      db_test:
        condition: service_healthy