version: '3.8'

services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${PG_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_PORT: ${PG_PORT}
      POSTGRES_DB: ${PG_DB}
      DRIVER: ${PG_DRIVER}
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      sh -c "
        export DATABASE_URL=postgresql+$${DRIVER}://root:root@$${POSTGRES_HOST}:5432/root &&
        alembic upgrade head && 
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy