"""initial

Revision ID: c82fcf26ede6
Revises: b4167d9dc1d2
Create Date: 2023-01-24 19:01:16.187099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82fcf26ede6'
down_revision = 'b4167d9dc1d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dish', ['id'])
    op.create_unique_constraint(None, 'menu', ['id'])
    op.drop_column('menu', 'dishes_count')
    op.drop_column('menu', 'submenus_count')
    op.create_unique_constraint(None, 'submenu', ['id'])
    op.drop_column('submenu', 'dishes_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenu', sa.Column('dishes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'submenu', type_='unique')
    op.add_column('menu', sa.Column('submenus_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('dishes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menu', type_='unique')
    op.drop_constraint(None, 'dish', type_='unique')
    # ### end Alembic commands ###
