"""initial

Revision ID: d4a4484d5b72
Revises: 99260a7ad50e
Create Date: 2023-01-25 21:04:52.703109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a4484d5b72'
down_revision = '99260a7ad50e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
